/**
 * PDF Guidelines Generator
 * Produces a structured brand guidelines document (content for PDF/HTML).
 */

import type { BrandStateObject } from "@/core/bso/types";

export interface GuidelinesSection {
  title: string;
  content: string;
  subsections?: GuidelinesSection[];
}

export function generateGuidelinesContent(bso: BrandStateObject): GuidelinesSection[] {
  const p = bso.product;
  const s = bso.strategy;
  const v = bso.visualIdentity;
  const verb = bso.verbalIdentity;

  const sections: GuidelinesSection[] = [];

  // ── 1. Brand Story ─────────────────────────────────
  sections.push({
    title: "1. Brand Story",
    content: [
      `## ${p.name}`,
      "",
      p.description,
      "",
      "### Mission",
      s.positioning || "To be defined.",
      "",
      "### Values",
      ...s.brandValues.map((v) => `- **${v}**`),
    ].join("\n"),
  });

  // ── 2. Logo Usage ──────────────────────────────────
  if (v.logo) {
    sections.push({
      title: "2. Logo Usage",
      content: [
        `**Logo Typology**: ${v.logo.typology}`,
        "",
        "### Clear Space",
        "Maintain minimum clear space equal to the height of the icon mark around all sides of the logo.",
        "",
        "### Minimum Size",
        "Digital: 24px height minimum. Print: 8mm height minimum.",
        "",
        "### Do Not:",
        "- Stretch or distort the logo",
        "- Change the logo colours",
        "- Add effects (shadows, gradients, outlines)",
        "- Rotate the logo",
        "- Place on busy backgrounds",
      ].join("\n"),
    });
  }

  // ── 3. Colour System ───────────────────────────────
  if (v.colourSystem) {
    const cs = v.colourSystem;
    sections.push({
      title: "3. Colour System",
      content: [
        `**Harmony Type**: ${cs.harmonyType}`,
        "",
        "### Primary Palette",
        `- **Primary** (60%): ${cs.primaryColour}`,
        `- **Secondary** (30%): ${cs.secondaryColour}`,
        `- **Accent** (10%): ${cs.accentColour}`,
        "",
        "### Accessibility",
        `WCAG 2.1 AA: **${cs.wcagReport.overall.toUpperCase()}**`,
      ].join("\n"),
    });
  }

  // ── 4. Typography ──────────────────────────────────
  if (v.typography) {
    const t = v.typography;
    sections.push({
      title: "4. Typography",
      content: [
        `**Display Font**: ${t.displayFont.name} (${t.displayFont.classification})`,
        `**Text Font**: ${t.textFont.name} (${t.textFont.classification})`,
        t.monoFont ? `**Mono Font**: ${t.monoFont.name}` : "",
        "",
        "### Type Scale",
        ...t.typeScale.sizes.map(
          (s) => `- **${s.name}**: ${s.sizePx}px / ${s.sizeRem}rem — ${s.usage}`
        ),
      ].filter(Boolean).join("\n"),
    });
  }

  // ── 5. Iconography ─────────────────────────────────
  if (v.iconography) {
    const ico = v.iconography;
    sections.push({
      title: "5. Iconography",
      content: [
        `**Style**: ${ico.fillApproach}, ${ico.strokeWeight}px stroke, ${ico.cornerRadius}px corners`,
        `**Grid**: ${ico.viewBox}×${ico.viewBox}px viewBox`,
        "",
        `**Core Icons**: ${ico.coreIcons.length} generated`,
        `**Feature Icons**: ${ico.featureIcons.length} generated`,
      ].join("\n"),
    });
  }

  // ── 6-10 continued...
  sections.push({
    title: "6. Illustration Style",
    content: v.illustrationStyle
      ? `**Style**: ${v.illustrationStyle.style}\n**Scenes**: ${v.illustrationStyle.sceneDescriptions.length} generated`
      : "To be defined.",
  });

  sections.push({
    title: "7. Motion Language",
    content: v.motionLanguage
      ? `**Personality**: ${v.motionLanguage.personality.duration} durations, ${v.motionLanguage.personality.easing} easing, ${v.motionLanguage.personality.style} style`
      : "To be defined.",
  });

  sections.push({
    title: "8. Tone of Voice",
    content: [
      `**Emotional Territory**: ${s.emotionalTerritory}`,
      `**Tone**: ${s.toneOfVoice.formalToCasual > 50 ? "Casual" : "Formal"}, ${s.toneOfVoice.seriousToWitty > 50 ? "Witty" : "Serious"}`,
    ].join("\n"),
  });

  sections.push({
    title: "9. Brand Applications",
    content: "Reference implementations across web, mobile, social, and print.",
  });

  sections.push({
    title: "10. Contact & Resources",
    content: [
      "This brand guidelines document was generated by VibeBranding.",
      `Generated: ${bso.metadata.createdAt}`,
      `Version: ${bso.version}`,
    ].join("\n"),
  });

  return sections;
}

export function generateGuidelinesMarkdown(bso: BrandStateObject): string {
  const sections = generateGuidelinesContent(bso);
  return sections.map((s) => s.content).join("\n\n---\n\n");
}
