/**
 * Brand Guidelines Module (Stage 8)
 *
 * Generates the complete brand guidelines document:
 * - 10 sections covering all aspects of the brand
 * - HTML + Markdown + PDF-ready content
 * - Ready for export and sharing
 */

import { getBsoStore } from "@/core/bso";
import { generateGuidelinesContent, generateGuidelinesMarkdown } from "@/export/pdf";
import type { AssetInfo } from "@/core/bso/types";

export interface GuidelinesOutput {
  success: boolean;
  sectionCount: number;
  markdown: string;
  totalWords: number;
}

/**
 * Generate the full brand guidelines document.
 * Uses the BSO and export module's guidelines generator.
 */
export function runGuidelines(): GuidelinesOutput {
  const store = getBsoStore();
  const bso = store.get();

  // Generate guidelines content
  const sections = generateGuidelinesContent(bso);
  const markdown = generateGuidelinesMarkdown(bso);

  // Update BSO stage
  store.update("assets", {
    exportFormats: [
      ...(bso.assets.exportFormats || []),
      "guidelines_md",
      "guidelines_html",
      "guidelines_pdf",
    ],
  } as Partial<AssetInfo>);

  store.advanceStage(); // Stage 8 → 9

  return {
    success: true,
    sectionCount: sections.length,
    markdown: markdown.slice(0, 500) + "...", // Truncated preview
    totalWords: markdown.split(/\s+/).length,
  };
}

/**
 * Generate the guidelines as HTML for preview/export.
 */
export function generateGuidelinesHTML(): string {
  const store = getBsoStore();
  const bso = store.get();
  const sections = generateGuidelinesContent(bso);

  const cs = bso.visualIdentity.colourSystem;
  const tp = bso.visualIdentity.typography;
  const primary = cs?.primaryColour || "#2563EB";
  const displayFont = tp?.displayFont.name || "system-ui";

  const sectionsHtml = sections
    .map(
      (s) => `
    <section class="guidelines-section">
      <h2>${s.title}</h2>
      <div class="section-content">${markdownToHtml(s.content)}</div>
    </section>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${bso.product.name} — Brand Guidelines</title>
  <style>
    :root {
      --brand-primary: ${primary};
      --brand-display: ${displayFont}, system-ui, sans-serif;
      --brand-text: ${tp?.textFont.name || "system-ui"}, sans-serif;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: var(--brand-text);
      line-height: 1.6;
      color: #1a1a2e;
      background: #fafafa;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    .cover {
      background: var(--brand-primary);
      color: white;
      padding: 80px 40px;
      text-align: center;
      border-radius: 16px;
      margin-bottom: 48px;
    }
    .cover h1 { font-family: var(--brand-display); font-size: 2.5rem; margin-bottom: 8px; }
    .cover p { font-size: 1.1rem; opacity: 0.9; }
    .guidelines-section {
      background: white;
      border-radius: 12px;
      padding: 32px;
      margin-bottom: 24px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.06);
    }
    .guidelines-section h2 {
      font-family: var(--brand-display);
      font-size: 1.5rem;
      color: var(--brand-primary);
      margin-bottom: 16px;
      padding-bottom: 8px;
      border-bottom: 2px solid var(--brand-primary);
    }
    .section-content h3 { font-size: 1.1rem; margin: 16px 0 8px; }
    .section-content p { margin-bottom: 12px; }
    .section-content ul { padding-left: 20px; margin-bottom: 12px; }
    .section-content li { margin-bottom: 4px; }
    .colour-swatch {
      display: inline-block;
      width: 48px;
      height: 48px;
      border-radius: 8px;
      margin-right: 8px;
      vertical-align: middle;
      border: 1px solid rgba(0,0,0,0.1);
    }
    .footer {
      text-align: center;
      padding: 32px;
      color: #94a3b8;
      font-size: 0.85rem;
    }
    @media print {
      body { background: white; }
      .guidelines-section { box-shadow: none; break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="cover">
    <h1>${bso.product.name}</h1>
    <p>Brand Guidelines — Generated by VibeBranding</p>
  </div>
  ${sectionsHtml}
  <div class="footer">
    <p>Generated ${new Date().toISOString().split("T")[0]} • VibeBranding v${bso.version}</p>
    <p>This is an AI-generated brand guidelines document. Review and adjust for your specific needs.</p>
  </div>
</body>
</html>`;
}

// ─── Helpers ─────────────────────────────────────────────────

function markdownToHtml(md: string): string {
  return md
    // Headers
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    // Bold
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    // Italic
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Lists (simple)
    .replace(/^- (.+)$/gm, "<li>$1</li>")
    .replace(/(<li>.*<\/li>\n?)+/g, "<ul>$&</ul>")
    // Paragraphs (double newlines)
    .replace(/\n\n/g, "</p><p>")
    // Wrap in paragraph if not already
    .replace(/^(?!<[hul])/gm, "<p>")
    .replace(/(?<![>])$/gm, "</p>")
    // Clean up empty tags
    .replace(/<p><\/p>/g, "")
    .replace(/<p><ul>/g, "<ul>")
    .replace(/<\/ul><\/p>/g, "</ul>");
}
