import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "VibeBranding Brand Identity — Our Story",
  description: "VibeBranding's own brand identity — generated by VibeBranding itself. Strategy, visual identity, voice, and the story behind the brand.",
  openGraph: {
    title: "VibeBranding Brand Identity — Our Story",
    description: "VibeBranding's own brand identity — generated by VibeBranding itself.",
  },
};

export default function BrandPage() {
  return (
    <main className="min-h-screen">
      {/* Hero */}
      <section className="border-b border-zinc-200 dark:border-zinc-800 bg-gradient-to-br from-blue-600 via-purple-600 to-blue-700 text-white">
        <div className="mx-auto max-w-5xl px-4 py-24 sm:px-6 lg:px-8 text-center">
          <h1 className="text-5xl font-bold tracking-tight sm:text-6xl mb-4">
            VibeBranding
          </h1>
          <p className="text-xl text-blue-100/90 font-medium mb-8">
            Our Brand Identity — Built with VibeBranding
          </p>
          <div className="flex items-center justify-center gap-6 text-sm text-blue-200/80">
            <span>✨ Self-branding case study</span>
            <span>🎯 Creator + Sage archetypes</span>
            <span>🎨 AI-generated identity</span>
          </div>
        </div>
      </section>

      <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8 space-y-16">
        {/* Strategy Section */}
        <section>
          <h2 className="text-2xl font-bold tracking-tight mb-2">Brand Strategy</h2>
          <p className="text-zinc-500 mb-8">
            VibeBranding was run through its own 9-stage pipeline. Here&apos;s what came back.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Archetypes</span>
              <div className="flex flex-wrap gap-2 mt-3">
                <span className="px-3 py-1.5 rounded-full bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 text-sm font-medium">
                  Creator 100%
                </span>
                <span className="px-3 py-1.5 rounded-full bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 text-sm font-medium">
                  Sage 85%
                </span>
              </div>
              <p className="text-sm text-zinc-600 dark:text-zinc-400 mt-3">
                The Creator archetype drives innovation and self-expression. The Sage brings wisdom and clarity. Together they form a brand that <em>builds tools for builders</em>.
              </p>
            </div>

            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Emotional Territory</span>
              <p className="text-xl font-bold mt-2 italic">Flow-State Craftsmanship</p>
              <p className="text-sm text-zinc-600 dark:text-zinc-400 mt-2">
                The feeling of being in the zone while making something beautiful. Calm focus, creative confidence, and the satisfaction of a well-crafted brand.
              </p>
            </div>

            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Brand Values</span>
              <div className="flex flex-wrap gap-1.5 mt-3">
                {["Clean Craftsmanship", "Code as Art", "In Action", "Developer-First", "Radical Clarity"].map((v) => (
                  <span key={v} className="px-2 py-0.5 rounded-md bg-zinc-100 dark:bg-zinc-800 text-xs">{v}</span>
                ))}
              </div>
            </div>

            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Tone of Voice</span>
              <div className="space-y-2 mt-3 text-sm">
                {[
                  { trait: "Confidence", value: 85 },
                  { trait: "Warmth", value: 70 },
                  { trait: "Playfulness", value: 60 },
                  { trait: "Precision", value: 90 },
                ].map((t) => (
                  <div key={t.trait} className="flex items-center gap-3">
                    <span className="w-24 text-zinc-500">{t.trait}</span>
                    <div className="flex-1 h-2 rounded-full bg-zinc-200 dark:bg-zinc-700">
                      <div className="h-2 rounded-full bg-blue-600" style={{ width: `${t.value}%` }} />
                    </div>
                    <span className="text-xs text-zinc-400 w-6 text-right">{t.value}%</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Visual Identity */}
        <section>
          <h2 className="text-2xl font-bold tracking-tight mb-2">Visual Identity</h2>
          <p className="text-zinc-500 mb-8">
            The colour palette and typography generated for VibeBranding.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Colour Palette</span>
              <div className="flex gap-4 mt-4">
                {[
                  { role: "Primary", hex: "#2563EB" },
                  { role: "Secondary", hex: "#7C3AED" },
                  { role: "Accent", hex: "#F59E0B" },
                ].map((c) => (
                  <div key={c.role} className="flex flex-col items-center gap-1.5">
                    <div
                      className="w-14 h-14 rounded-xl shadow-md border border-zinc-200 dark:border-zinc-700"
                      style={{ backgroundColor: c.hex }}
                    />
                    <span className="text-[10px] text-zinc-500">{c.role}</span>
                    <span className="text-[10px] font-mono text-zinc-400">{c.hex}</span>
                  </div>
                ))}
              </div>
              <p className="text-xs text-zinc-500 mt-4">
                Harmony: Triadic • WCAG: AA Passed • 60-30-10 distribution
              </p>
            </div>

            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Typography</span>
              <div className="mt-4 space-y-3">
                <div>
                  <p className="text-2xl font-bold" style={{ fontFamily: "Geist, system-ui, sans-serif" }}>
                    Geist
                  </p>
                  <p className="text-xs text-zinc-400">Display — Bold, heavy weights for headlines</p>
                </div>
                <div>
                  <p className="text-base" style={{ fontFamily: "Geist, system-ui, sans-serif" }}>
                    Geist Text
                  </p>
                  <p className="text-xs text-zinc-400">Body — Regular weight for reading</p>
                </div>
                <div>
                  <p className="text-sm font-mono">Geist Mono</p>
                  <p className="text-xs text-zinc-400">Code — For technical content and UI labels</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Voice */}
        <section>
          <h2 className="text-2xl font-bold tracking-tight mb-2">Brand Voice</h2>
          <p className="text-zinc-500 mb-8">
            Generated taglines, messaging, and verbal identity.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Hero Headline</span>
              <p className="text-xl font-bold italic mt-2">&ldquo;Your brand identity, one prompt away.&rdquo;</p>
            </div>

            <div className="rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
              <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Primary CTA</span>
              <span className="inline-block mt-3 px-5 py-2.5 rounded-lg bg-blue-600 text-white text-sm font-semibold">
                Generate Your Brand
              </span>
            </div>
          </div>

          <div className="mt-6 rounded-xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 shadow-sm">
            <span className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">Taglines</span>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
              {[
                { text: "Brand identity, AI-powered", score: 8.5 },
                { text: "From idea to identity", score: 8.0 },
                { text: "Built for builders", score: 7.5 },
                { text: "Your brand, your vibe", score: 7.0 },
              ].map((t) => (
                <div key={t.text} className="flex items-center gap-2 text-sm text-zinc-600 dark:text-zinc-400">
                  <span className="text-lg">"{t.text}"</span>
                  <span className="text-xs text-zinc-400 ml-auto">{t.score}/10</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Export */}
        <section>
          <h2 className="text-2xl font-bold tracking-tight mb-2">Brand Kit</h2>
          <p className="text-zinc-500 mb-6">
            VibeBranding&apos;s own brand tokens are available in all export formats.
          </p>

          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
            {[
              { label: "CSS Tokens", format: "css" },
              { label: "Tailwind Config", format: "tailwind" },
              { label: "SCSS Variables", format: "scss" },
              { label: "Figma Styles", format: "figma" },
              { label: "HTML Guidelines", format: "html" },
            ].map((f) => (
              <div
                key={f.format}
                className="rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 px-4 py-3 text-sm font-medium text-zinc-600 dark:text-zinc-400 text-center"
              >
                {f.label}
              </div>
            ))}
          </div>

          <p className="mt-6 text-sm text-zinc-500 bg-zinc-50 dark:bg-zinc-900/50 rounded-xl p-4 border border-zinc-200 dark:border-zinc-800">
            <strong>Note:</strong> Full brand kit export runs from the{' '}
            <Link href="/" className="text-blue-600 hover:text-blue-700 font-medium underline">brand generator</Link>.
            Generate a brand identity, then download from the Export section.
          </p>
        </section>

        {/* Process */}
        <section>
          <h2 className="text-2xl font-bold tracking-tight mb-2">The Process</h2>
          <p className="text-zinc-500 mb-8">
            How VibeBranding built its own brand — a meta case study in AI-powered brand creation.
          </p>

          <div className="space-y-6">
            {[
              {
                stage: 1,
                title: "Discovery",
                desc: "We described VibeBranding to itself: 'AI-driven brand identity generation platform for vibe-coded products, indie apps, SaaS tools, and developer-built projects.' Positioning analysis identified the target audience of builders and creators who need quick, coherent brand identity systems.",
              },
              {
                stage: 2,
                title: "Strategy",
                desc: "The pipeline identified Creator (100%) and Sage (85%) as the primary archetypes — a brand that both builds and teaches. The emotional territory of 'Flow-State Craftsmanship' perfectly captures the experience of designing in the zone.",
              },
              {
                stage: 3,
                title: "Naming",
                desc: "The name 'VibeBranding' was chosen before the pipeline run. The naming module would generate alternatives and validate against trademark risks, phonetic memorability, and domain availability.",
              },
              {
                stage: 4,
                title: "Visual Identity",
                desc: "The colour system uses a triadic harmony of blue (#2563EB), purple (#7C3AED), and amber (#F59E0B). Geist font family (sans + mono) for clean, developer-friendly typography. WCAG AA compliant.",
              },
              {
                stage: 5,
                title: "Logo & Assets",
                desc: "Iconography uses 1.5px stroke weight with rounded corners — friendly but precise. Motion language: 300ms standard duration, ease-in-out. SVG logo generation with Recraft V4.1 available with Replicate billing.",
              },
              {
                stage: 6,
                title: "Voice & Launch",
                desc: "Verbal identity centers on the hero headline 'Your brand identity, one prompt away.' Primary CTA: 'Generate Your Brand.' Full brand guidelines exportable as PDF, HTML, CSS tokens, Tailwind config, SCSS variables, and Figma styles.",
              },
            ].map((s) => (
              <div key={s.stage} className="flex gap-4">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center text-sm font-bold">
                  {s.stage}
                </div>
                <div>
                  <h3 className="font-semibold">{s.title}</h3>
                  <p className="text-sm text-zinc-500 mt-1">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section className="text-center py-8">
          <h2 className="text-2xl font-bold tracking-tight mb-3">Build Your Own Brand</h2>
          <p className="text-zinc-500 mb-6 max-w-lg mx-auto">
            VibeBranding built its own identity in minutes. Your product deserves the same treatment.
          </p>
          <Link
            href="/"
            className="inline-block px-8 py-4 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-base transition-colors shadow-lg shadow-blue-600/25"
          >
            Generate Your Brand Identity →
          </Link>
        </section>
      </div>
    </main>
  );
}
